# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
###############################################
# Multi-stage build Dockerfile for mcp-server-web3
###############################################

# Stage 1: build the project
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy package files and install all dependencies including devDependencies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy the rest of the project and build
COPY . .
RUN yarn build

# Stage 2: create production image
FROM node:lts-alpine
WORKDIR /app

# Install production dependencies only
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile

# Copy built files from builder stage
COPY --from=builder /app/build ./build

# Expose port if needed
# EXPOSE 3000

CMD ["node", "build/index.js"]
